'use client';

import { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const translations = {
  en: {
    // Navbar
    home: 'Home',
    cars: 'Cars',
    about: 'About',
    contact: 'Contact',
    brand: 'DreamCars',
    
    // Hero
    herobadge: 'Over 500+ Premium Cars Available',
    heroTitle1: 'Find Your',
    heroTitle2: 'Dream Car',
    heroSubtitle: 'Discover the perfect vehicle from our curated collection of premium cars. Quality, luxury, and reliability in every choice.',
    browseCars: 'Browse Cars',
    contactUs: 'Contact Us',
    
    // Stats
    carsAvailable: 'Cars Available',
    happyCustomers: 'Happy Customers',
    yearsExperience: 'Years Experience',
    expertTeam: 'Expert Team',
    
    // Featured Cars
    ourCollection: 'Our Collection',
    featuredCars: 'Featured Cars',
    featuredDesc: 'Browse our handpicked selection of premium vehicles. Each car is thoroughly inspected and ready for delivery.',
    viewDetails: 'View Details',
    viewAllCars: 'View All Cars',
    power: 'Power',
    topSpeed: 'Top Speed',
    range: 'Range',
    
    // About
    aboutUs: 'About Us',
    aboutTitle1: 'Your Trusted Partner in',
    aboutTitle2: 'Premium Cars',
    aboutText1: 'With over 15 years of experience in the automotive industry, we have helped thousands of customers find their perfect vehicle. Our commitment to quality, transparency, and customer satisfaction sets us apart.',
    aboutText2: 'Whether you are looking for a luxury sedan, a powerful sports car, or an eco-friendly electric vehicle, our expert team is here to guide you through every step of the journey.',
    qualityAssured: 'Quality Assured',
    qualityDesc: 'Every vehicle undergoes rigorous inspection',
    bestPrices: 'Best Prices',
    bestPricesDesc: 'Competitive pricing with flexible financing',
    expertTeamTitle: 'Expert Team',
    expertTeamDesc: 'Professional guidance every step of the way',
    fastDelivery: 'Fast Delivery',
    fastDeliveryDesc: 'Quick processing and delivery to your door',
    learnMore: 'Learn More About Us',
    
    // Contact
    readyToFind: 'Ready to Find Your Dream Car?',
    contactDesc: 'Visit our showroom or get in touch with our expert team. We are here to help you find the perfect vehicle that matches your style and budget.',
    callUs: 'Call Us',
    emailUs: 'Email Us',
    visitUs: 'Visit Us',
    scheduleVisit: 'Schedule a Visit',
    getQuote: 'Get a Quote',
    
    // Footer
    footerDesc: 'Your trusted partner in finding the perfect vehicle. Quality, luxury, and reliability in every choice.',
    company: 'Company',
    services: 'Services',
    support: 'Support',
    legal: 'Legal',
    newsletter: 'Subscribe to Our Newsletter',
    newsleterDesc: 'Get the latest updates on new cars and exclusive offers.',
    emailPlaceholder: 'Enter your email',
    subscribe: 'Subscribe',
    allRightsReserved: 'All rights reserved',
    privacyPolicy: 'Privacy Policy',
    termsOfService: 'Terms of Service',
    sitemap: 'Sitemap',
    
    // About Page
    aboutPageTitle: 'About Us',
    aboutPageSlogan: 'Driving Excellence Since 2009',
    ourMission: 'Our Mission',
    missionText: 'To provide exceptional automotive solutions through quality vehicles, transparent pricing, and unmatched customer service. We believe every journey begins with the right vehicle.',
    ourVision: 'Our Vision',
    visionText: 'To become the most trusted automotive partner by revolutionizing the car buying experience with innovation, integrity, and customer-first approach.',
    ourHistory: 'Our History',
    historyText: 'Founded in 2009, DreamCars has grown from a small family business to one of the region\'s leading car agencies. Our journey has been built on trust, quality, and a passion for automobiles.',
    whyChooseUs: 'Why Choose Us',
    whyChooseDesc: 'We stand out through our commitment to excellence and customer satisfaction',
    certifiedQuality: 'Certified Quality',
    certifiedQualityDesc: 'All vehicles undergo comprehensive 150-point inspection',
    transparentPricing: 'Transparent Pricing',
    transparentPricingDesc: 'No hidden fees, clear pricing with detailed breakdowns',
    lifetimeSupport: 'Lifetime Support',
    lifetimeSupportDesc: '24/7 customer service and maintenance assistance',
    flexibleFinancing: 'Flexible Financing',
    flexibleFinancingDesc: 'Customized payment plans to fit your budget',
    ourServices: 'Our Services',
    servicesDesc: 'Comprehensive automotive solutions for all your needs',
    carSales: 'Car Sales',
    carSalesDesc: 'Wide selection of new and certified pre-owned vehicles from top brands',
    financing: 'Financing',
    financingDesc: 'Competitive rates and flexible payment options tailored to you',
    tradeIn: 'Trade-In',
    tradeInDesc: 'Fair market value for your current vehicle with instant quotes',
    maintenance: 'Maintenance & Service',
    maintenanceDesc: 'Expert technicians and genuine parts for all makes and models',
    insurance: 'Insurance',
    insuranceDesc: 'Comprehensive coverage options from trusted insurance partners',
    warranty: 'Extended Warranty',
    warrantyDesc: 'Peace of mind with our comprehensive warranty programs',
    meetOurTeam: 'Meet Our Expert Team',
    teamDesc: 'Dedicated professionals committed to your automotive needs',
    salesDirector: 'Sales Director',
    serviceManager: 'Service Manager',
    financeAdvisor: 'Finance Advisor',
    customerRelations: 'Customer Relations',
    getInTouch: 'Get In Touch',
    getInTouchDesc: 'Visit our showroom or contact us for any inquiries',
    ourLocation: 'Our Location',
    businessHours: 'Business Hours',
    mondayFriday: 'Monday - Friday',
    saturday: 'Saturday',
    sunday: 'Sunday',
    viewOnMap: 'View on Google Maps',
    
    // Cars Page
    availableCars: 'Available Cars',
    browseCars: 'Browse Cars',
    carsPageDesc: 'Discover your perfect vehicle from our extensive collection',
    searchPlaceholder: 'Search by brand, model, or year...',
    filters: 'Filters',
    allBrands: 'All Brands',
    allModels: 'All Models',
    allYears: 'All Years',
    fuelType: 'Fuel Type',
    allFuelTypes: 'All Fuel Types',
    transmission: 'Transmission',
    allTransmissions: 'All Transmissions',
    priceRange: 'Price Range',
    minPrice: 'Min Price',
    maxPrice: 'Max Price',
    resetFilters: 'Reset Filters',
    applyFilters: 'Apply Filters',
    sortBy: 'Sort By',
    priceLowToHigh: 'Price: Low to High',
    priceHighToLow: 'Price: High to Low',
    yearNewest: 'Year: Newest First',
    yearOldest: 'Year: Oldest First',
    brandAZ: 'Brand: A-Z',
    brandZA: 'Brand: Z-A',
    showingResults: 'Showing',
    of: 'of',
    results: 'results',
    noResults: 'No cars found',
    noResultsDesc: 'Try adjusting your filters or search terms',
    clearFilters: 'Clear All Filters',
    new: 'New',
    used: 'Used',
    certified: 'Certified Pre-Owned',
    electric: 'Electric',
    hybrid: 'Hybrid',
    gasoline: 'Gasoline',
    diesel: 'Diesel',
    automatic: 'Automatic',
    manual: 'Manual',
    semiAutomatic: 'Semi-Automatic',
    loadMore: 'Load More',
    loading: 'Loading...',
    perPage: 'Per Page',
    startingPrice: 'Starting Price',
    allConditions: 'All Conditions',
    condition: 'Condition',
    
    // Car Details Page
    carDetails: 'Car Details',
    specifications: 'Specifications',
    features: 'Features & Equipment',
    description: 'Description',
    overview: 'Overview',
    version: 'Version',
    doors: 'Doors',
    seats: 'Seats',
    engineCapacity: 'Engine',
    vinNumber: 'VIN Number',
    availability: 'Availability',
    available: 'Available',
    reserved: 'Reserved',
    sold: 'Sold',
    discount: 'Discount',
    finalPrice: 'Final Price',
    reserveNow: 'Reserve Now',
    buyNow: 'Buy Now',
    contactDealer: 'Contact Dealer',
    shareThisCar: 'Share This Car',
    printDetails: 'Print Details',
    compareVehicles: 'Compare Vehicles',
    scheduleTestDrive: 'Schedule Test Drive',
    financing: 'Financing Options',
    tradeIn: 'Trade-In Value',
    warranty: 'Warranty Information',
    luxuryPerformance: 'Luxury and Performance',
    premiumFeatures: 'Premium Features',
    advancedTech: 'Advanced Technology',
    exceptionalComfort: 'Exceptional Comfort',
    
    // Contact Page
    contactUs: 'Contact Us',
    getInTouch: 'Get in Touch',
    contactDescription: 'Have a question or want to schedule a test drive? We\'re here to help! Reach out to us and our team will get back to you as soon as possible.',
    contactInfo: 'Contact Information',
    ourLocation: 'Our Location',
    sendMessage: 'Send us a Message',
    fullName: 'Full Name',
    email: 'Email Address',
    phone: 'Phone Number',
    subject: 'Subject',
    message: 'Message',
    submit: 'Send Message',
    submitting: 'Sending...',
    messageSent: 'Message sent successfully!',
    messageError: 'Failed to send message. Please try again.',
    address: 'Address',
    workingHours: 'Working Hours',
    mondayFriday: 'Monday - Friday',
    saturday: 'Saturday',
    sunday: 'Sunday',
    closed: 'Closed',
    callUs: 'Call Us',
    emailUs: 'Email Us',
    visitUs: 'Visit Us',
    followUs: 'Follow Us',
    generalInquiry: 'General Inquiry',
    testDrive: 'Test Drive Request',
    salesQuestion: 'Sales Question',
    serviceSupport: 'Service & Support',
    other: 'Other',
    required: 'This field is required',
    invalidEmail: 'Please enter a valid email address',
    invalidPhone: 'Please enter a valid phone number',
    
    // Registration/Inscription Page
    clientRegistration: 'Client Registration',
    inscription: 'Inscription',
    registrationDescription: 'Complete the form below to register and reserve your dream car. All fields marked with * are required.',
    personalInfo: 'Personal Information',
    nationality: 'Nationality',
    nationalId: 'National ID / Passport Number',
    streetAddress: 'Street Address',
    city: 'City',
    country: 'Country',
    zipCode: 'ZIP / Postal Code',
    carSelection: 'Car Selection',
    selectCar: 'Select a Car',
    selectedCar: 'Selected Car',
    noCar: 'No car selected',
    carPrice: 'Car Price',
    paymentInfo: 'Payment Information',
    paymentMethod: 'Payment Method',
    cash: 'Cash',
    bankTransfer: 'Bank Transfer',
    creditCard: 'Credit Card',
    financing: 'Financing',
    paymentAmount: 'Payment Amount',
    referenceNumber: 'Reference Number',
    transactionId: 'Transaction ID',
    documentUpload: 'Document Upload',
    uploadDocuments: 'Upload Required Documents',
    idCard: 'ID Card / Passport',
    driversLicense: 'Driver\'s License',
    proofOfResidence: 'Proof of Residence',
    paymentProof: 'Payment Proof',
    uploadFile: 'Upload File',
    fileUploaded: 'File Uploaded',
    removeFile: 'Remove File',
    dragDrop: 'Drag and drop or click to upload',
    termsAndConditions: 'Terms & Conditions',
    acceptTerms: 'I accept the Terms and Conditions and Privacy Policy',
    signature: 'Signature',
    typeYourName: 'Type your full name as signature',
    confirmRegistration: 'Confirm Registration',
    processing: 'Processing...',
    registrationSuccess: 'Registration Successful!',
    registrationError: 'Registration failed. Please try again.',
    certificateGenerated: 'Your Certificate of Inscription has been generated successfully.',
    trackingCode: 'Tracking Code',
    downloadCertificate: 'Download Certificate',
    registrationSummary: 'Registration Summary',
    backToHome: 'Back to Home',
    stepOf: 'Step {current} of {total}',
    next: 'Next',
    previous: 'Previous',
    dateOfBirth: 'Date of Birth',
    gender: 'Gender',
    male: 'Male',
    female: 'Female',
    preferNotToSay: 'Prefer not to say',
  },
  fr: {
    // Navbar
    home: 'Accueil',
    cars: 'Voitures',
    about: 'À Propos',
    contact: 'Contact',
    brand: 'DreamCars',
    
    // Hero
    heroTitle1: 'Trouvez Votre',
    heroTitle2: 'Voiture de Rêve',
    heroSubtitle: 'Découvrez le véhicule parfait parmi notre collection de voitures premium. Qualité, luxe et fiabilité dans chaque choix.',
    browseCars: 'Parcourir les Voitures',
    contactUs: 'Contactez-nous',
    herobadge: 'Plus de 500 voitures premium disponibles',
    
    // Stats
    carsAvailable: 'Voitures Disponibles',
    happyCustomers: 'Clients Satisfaits',
    yearsExperience: 'Années d\'Expérience',
    expertTeam: 'Équipe d\'Experts',
    
    // Featured Cars
    ourCollection: 'Notre Collection',
    featuredCars: 'Voitures en Vedette',
    featuredDesc: 'Parcourez notre sélection de véhicules premium. Chaque voiture est soigneusement inspectée et prête à être livrée.',
    viewDetails: 'Voir Détails',
    viewAllCars: 'Voir Toutes les Voitures',
    power: 'Puissance',
    topSpeed: 'Vitesse Max',
    range: 'Autonomie',
    
    // About
    aboutUs: 'À Propos',
    aboutTitle1: 'Votre Partenaire de Confiance en',
    aboutTitle2: 'Voitures Premium',
    aboutText1: 'Avec plus de 15 ans d\'expérience dans l\'industrie automobile, nous avons aidé des milliers de clients à trouver leur véhicule parfait. Notre engagement envers la qualité, la transparence et la satisfaction client nous distingue.',
    aboutText2: 'Que vous recherchiez une berline de luxe, une voiture de sport puissante ou un véhicule électrique écologique, notre équipe d\'experts est là pour vous guider à chaque étape.',
    qualityAssured: 'Qualité Garantie',
    qualityDesc: 'Chaque véhicule subit une inspection rigoureuse',
    bestPrices: 'Meilleurs Prix',
    bestPricesDesc: 'Prix compétitifs avec financement flexible',
    expertTeamTitle: 'Équipe d\'Experts',
    expertTeamDesc: 'Conseils professionnels à chaque étape',
    fastDelivery: 'Livraison Rapide',
    fastDeliveryDesc: 'Traitement et livraison rapides à votre porte',
    learnMore: 'En Savoir Plus',
    
    // Contact
    readyToFind: 'Prêt à Trouver Votre Voiture de Rêve?',
    contactDesc: 'Visitez notre salle d\'exposition ou contactez notre équipe d\'experts. Nous sommes là pour vous aider à trouver le véhicule parfait qui correspond à votre style et votre budget.',
    callUs: 'Appelez-nous',
    emailUs: 'Envoyez-nous un Email',
    visitUs: 'Visitez-nous',
    scheduleVisit: 'Planifier une Visite',
    getQuote: 'Obtenir un Devis',
    
    // Footer
    footerDesc: 'Votre partenaire de confiance pour trouver le véhicule parfait. Qualité, luxe et fiabilité dans chaque choix.',
    company: 'Entreprise',
    services: 'Services',
    support: 'Support',
    legal: 'Légal',
    newsletter: 'Abonnez-vous à Notre Newsletter',
    newsleterDesc: 'Recevez les dernières mises à jour sur les nouvelles voitures et offres exclusives.',
    emailPlaceholder: 'Entrez votre email',
    subscribe: 'S\'abonner',
    allRightsReserved: 'Tous droits réservés',
    privacyPolicy: 'Politique de Confidentialité',
    termsOfService: 'Conditions d\'Utilisation',
    sitemap: 'Plan du Site',
    
    // About Page
    aboutPageTitle: 'À Propos de Nous',
    aboutPageSlogan: 'Excellence en Conduite Depuis 2009',
    ourMission: 'Notre Mission',
    missionText: 'Fournir des solutions automobiles exceptionnelles à travers des véhicules de qualité, des prix transparents et un service client inégalé. Nous croyons que chaque voyage commence avec le bon véhicule.',
    ourVision: 'Notre Vision',
    visionText: 'Devenir le partenaire automobile le plus fiable en révolutionnant l\'expérience d\'achat de voiture avec innovation, intégrité et approche centrée sur le client.',
    ourHistory: 'Notre Histoire',
    historyText: 'Fondée en 2009, DreamCars est passée d\'une petite entreprise familiale à l\'une des principales agences automobiles de la région. Notre parcours a été construit sur la confiance, la qualité et la passion pour l\'automobile.',
    whyChooseUs: 'Pourquoi Nous Choisir',
    whyChooseDesc: 'Nous nous distinguons par notre engagement envers l\'excellence et la satisfaction client',
    certifiedQuality: 'Qualité Certifiée',
    certifiedQualityDesc: 'Tous les véhicules subissent une inspection complète en 150 points',
    transparentPricing: 'Prix Transparents',
    transparentPricingDesc: 'Aucun frais caché, prix clairs avec détails complets',
    lifetimeSupport: 'Support à Vie',
    lifetimeSupportDesc: 'Service client 24/7 et assistance maintenance',
    flexibleFinancing: 'Financement Flexible',
    flexibleFinancingDesc: 'Plans de paiement personnalisés adaptés à votre budget',
    ourServices: 'Nos Services',
    servicesDesc: 'Solutions automobiles complètes pour tous vos besoins',
    carSales: 'Vente de Voitures',
    carSalesDesc: 'Large sélection de véhicules neufs et d\'occasion certifiés des meilleures marques',
    financing: 'Financement',
    financingDesc: 'Taux compétitifs et options de paiement flexibles adaptées à vous',
    tradeIn: 'Reprise',
    tradeInDesc: 'Valeur marchande équitable pour votre véhicule actuel avec devis instantané',
    maintenance: 'Maintenance & Service',
    maintenanceDesc: 'Techniciens experts et pièces d\'origine pour toutes marques et modèles',
    insurance: 'Assurance',
    insuranceDesc: 'Options de couverture complète avec des partenaires d\'assurance de confiance',
    warranty: 'Garantie Étendue',
    warrantyDesc: 'Tranquillité d\'esprit avec nos programmes de garantie complets',
    meetOurTeam: 'Rencontrez Notre Équipe',
    teamDesc: 'Professionnels dédiés à vos besoins automobiles',
    salesDirector: 'Directeur des Ventes',
    serviceManager: 'Responsable Service',
    financeAdvisor: 'Conseiller Financier',
    customerRelations: 'Relations Client',
    getInTouch: 'Contactez-Nous',
    getInTouchDesc: 'Visitez notre showroom ou contactez-nous pour toute demande',
    ourLocation: 'Notre Emplacement',
    businessHours: 'Heures d\'Ouverture',
    mondayFriday: 'Lundi - Vendredi',
    saturday: 'Samedi',
    sunday: 'Dimanche',
    viewOnMap: 'Voir sur Google Maps',
    
    // Cars Page
    availableCars: 'Voitures Disponibles',
    browseCars: 'Parcourir les Voitures',
    carsPageDesc: 'Découvrez votre véhicule parfait dans notre vaste collection',
    searchPlaceholder: 'Rechercher par marque, modèle ou année...',
    filters: 'Filtres',
    allBrands: 'Toutes les Marques',
    allModels: 'Tous les Modèles',
    allYears: 'Toutes les Années',
    fuelType: 'Type de Carburant',
    allFuelTypes: 'Tous les Carburants',
    transmission: 'Transmission',
    allTransmissions: 'Toutes les Transmissions',
    priceRange: 'Gamme de Prix',
    minPrice: 'Prix Min',
    maxPrice: 'Prix Max',
    resetFilters: 'Réinitialiser',
    applyFilters: 'Appliquer',
    sortBy: 'Trier Par',
    priceLowToHigh: 'Prix: Croissant',
    priceHighToLow: 'Prix: Décroissant',
    yearNewest: 'Année: Plus Récent',
    yearOldest: 'Année: Plus Ancien',
    brandAZ: 'Marque: A-Z',
    brandZA: 'Marque: Z-A',
    showingResults: 'Affichage',
    of: 'sur',
    results: 'résultats',
    noResults: 'Aucune voiture trouvée',
    noResultsDesc: 'Essayez d\'ajuster vos filtres ou termes de recherche',
    clearFilters: 'Effacer Tous les Filtres',
    new: 'Neuf',
    used: 'Occasion',
    certified: 'Certifié d\'Occasion',
    electric: 'Électrique',
    hybrid: 'Hybride',
    gasoline: 'Essence',
    diesel: 'Diesel',
    automatic: 'Automatique',
    manual: 'Manuelle',
    semiAutomatic: 'Semi-Automatique',
    loadMore: 'Charger Plus',
    loading: 'Chargement...',
    perPage: 'Par Page',
    startingPrice: 'Prix de Départ',
    allConditions: 'Toutes les Conditions',
    condition: 'État',
    
    // Car Details Page
    carDetails: 'Détails de la Voiture',
    specifications: 'Spécifications',
    features: 'Équipements & Fonctionnalités',
    description: 'Description',
    overview: 'Aperçu',
    version: 'Version',
    doors: 'Portes',
    seats: 'Sièges',
    engineCapacity: 'Moteur',
    vinNumber: 'Numéro VIN',
    availability: 'Disponibilité',
    available: 'Disponible',
    reserved: 'Réservé',
    sold: 'Vendu',
    discount: 'Remise',
    finalPrice: 'Prix Final',
    reserveNow: 'Réserver Maintenant',
    buyNow: 'Acheter Maintenant',
    contactDealer: 'Contacter le Concessionnaire',
    shareThisCar: 'Partager Cette Voiture',
    printDetails: 'Imprimer les Détails',
    compareVehicles: 'Comparer les Véhicules',
    scheduleTestDrive: 'Planifier un Essai',
    financing: 'Options de Financement',
    tradeIn: 'Valeur de Reprise',
    warranty: 'Informations sur la Garantie',
    luxuryPerformance: 'Luxe et Performance',
    premiumFeatures: 'Fonctionnalités Premium',
    advancedTech: 'Technologie Avancée',
    exceptionalComfort: 'Confort Exceptionnel',
    
    // Contact Page
    contactUs: 'Nous Contacter',
    getInTouch: 'Entrer en Contact',
    contactDescription: 'Vous avez une question ou souhaitez planifier un essai ? Nous sommes là pour vous aider ! Contactez-nous et notre équipe vous répondra dans les plus brefs délais.',
    contactInfo: 'Informations de Contact',
    ourLocation: 'Notre Emplacement',
    sendMessage: 'Envoyez-nous un Message',
    fullName: 'Nom Complet',
    email: 'Adresse Email',
    phone: 'Numéro de Téléphone',
    subject: 'Sujet',
    message: 'Message',
    submit: 'Envoyer le Message',
    submitting: 'Envoi en cours...',
    messageSent: 'Message envoyé avec succès !',
    messageError: 'Échec de l\'envoi du message. Veuillez réessayer.',
    
    // Registration/Inscription Page
    clientRegistration: 'Inscription Client',
    inscription: 'Inscription',
    registrationDescription: 'Remplissez le formulaire ci-dessous pour vous inscrire et réserver la voiture de vos rêves. Tous les champs marqués d\'un * sont obligatoires.',
    personalInfo: 'Informations Personnelles',
    nationality: 'Nationalité',
    nationalId: 'Numéro de CNI / Passeport',
    streetAddress: 'Adresse',
    city: 'Ville',
    country: 'Pays',
    zipCode: 'Code Postal',
    carSelection: 'Sélection de Voiture',
    selectCar: 'Sélectionner une Voiture',
    selectedCar: 'Voiture Sélectionnée',
    noCar: 'Aucune voiture sélectionnée',
    carPrice: 'Prix de la Voiture',
    paymentInfo: 'Informations de Paiement',
    paymentMethod: 'Méthode de Paiement',
    cash: 'Espèces',
    bankTransfer: 'Virement Bancaire',
    creditCard: 'Carte de Crédit',
    financing: 'Financement',
    paymentAmount: 'Montant du Paiement',
    referenceNumber: 'Numéro de Référence',
    transactionId: 'ID de Transaction',
    documentUpload: 'Téléchargement de Documents',
    uploadDocuments: 'Télécharger les Documents Requis',
    idCard: 'Carte d\'Identité / Passeport',
    driversLicense: 'Permis de Conduire',
    proofOfResidence: 'Justificatif de Domicile',
    paymentProof: 'Preuve de Paiement',
    uploadFile: 'Télécharger le Fichier',
    fileUploaded: 'Fichier Téléchargé',
    removeFile: 'Supprimer le Fichier',
    dragDrop: 'Glissez-déposez ou cliquez pour télécharger',
    termsAndConditions: 'Termes et Conditions',
    acceptTerms: 'J\'accepte les Termes et Conditions et la Politique de Confidentialité',
    signature: 'Signature',
    typeYourName: 'Tapez votre nom complet comme signature',
    confirmRegistration: 'Confirmer l\'Inscription',
    processing: 'Traitement en cours...',
    registrationSuccess: 'Inscription Réussie !',
    registrationError: 'Échec de l\'inscription. Veuillez réessayer.',
    certificateGenerated: 'Votre Certificat d\'Inscription a été généré avec succès.',
    trackingCode: 'Code de Suivi',
    downloadCertificate: 'Télécharger le Certificat',
    registrationSummary: 'Résumé de l\'Inscription',
    backToHome: 'Retour à l\'Accueil',
    stepOf: 'Étape {current} sur {total}',
    next: 'Suivant',
    previous: 'Précédent',
    dateOfBirth: 'Date de Naissance',
    gender: 'Genre',
    male: 'Homme',
    female: 'Femme',
    preferNotToSay: 'Préfère ne pas dire',
    address: 'Adresse',
    workingHours: 'Heures d\'Ouverture',
    mondayFriday: 'Lundi - Vendredi',
    saturday: 'Samedi',
    sunday: 'Dimanche',
    closed: 'Fermé',
    callUs: 'Appelez-Nous',
    emailUs: 'Envoyez-nous un Email',
    visitUs: 'Visitez-Nous',
    followUs: 'Suivez-Nous',
    generalInquiry: 'Demande Générale',
    testDrive: 'Demande d\'Essai',
    salesQuestion: 'Question de Vente',
    serviceSupport: 'Service et Support',
    other: 'Autre',
    required: 'Ce champ est requis',
    invalidEmail: 'Veuillez entrer une adresse email valide',
    invalidPhone: 'Veuillez entrer un numéro de téléphone valide',
  },
  ar: {
    // Navbar
    home: 'الرئيسية',
    cars: 'السيارات',
    about: 'معلومات عنا',
    contact: 'اتصل بنا',
    brand: 'دريم كارز',
    
    // Hero
    heroTitle1: 'اعثر على',
    heroTitle2: 'سيارة أحلامك',
    heroSubtitle: 'اكتشف السيارة المثالية من مجموعتنا المنتقاة من السيارات الفاخرة. الجودة والفخامة والموثوقية في كل اختيار.',
    browseCars: 'تصفح السيارات',
    contactUs: 'اتصل بنا',
    herobadge: 'أكثر من 500 سيارة فاخرة متوفرة',
    
    // Stats
    carsAvailable: 'سيارات متوفرة',
    happyCustomers: 'عملاء سعداء',
    yearsExperience: 'سنوات خبرة',
    expertTeam: 'فريق خبراء',
    
    // Featured Cars
    ourCollection: 'مجموعتنا',
    featuredCars: 'السيارات المميزة',
    featuredDesc: 'تصفح مجموعتنا المختارة من السيارات الفاخرة. كل سيارة تم فحصها بدقة وجاهزة للتسليم.',
    viewDetails: 'عرض التفاصيل',
    viewAllCars: 'عرض جميع السيارات',
    power: 'القوة',
    topSpeed: 'السرعة القصوى',
    range: 'المدى',
    
    // About
    aboutUs: 'معلومات عنا',
    aboutTitle1: 'شريكك الموثوق في',
    aboutTitle2: 'السيارات الفاخرة',
    aboutText1: 'مع أكثر من 15 عامًا من الخبرة في صناعة السيارات، ساعدنا آلاف العملاء في العثور على سيارتهم المثالية. التزامنا بالجودة والشفافية ورضا العملاء يميزنا.',
    aboutText2: 'سواء كنت تبحث عن سيارة سيدان فاخرة أو سيارة رياضية قوية أو سيارة كهربائية صديقة للبيئة، فريقنا من الخبراء هنا لإرشادك في كل خطوة.',
    qualityAssured: 'الجودة مضمونة',
    qualityDesc: 'كل سيارة تخضع لفحص دقيق',
    bestPrices: 'أفضل الأسعار',
    bestPricesDesc: 'أسعار تنافسية مع تمويل مرن',
    expertTeamTitle: 'فريق الخبراء',
    expertTeamDesc: 'إرشاد مهني في كل خطوة',
    fastDelivery: 'تسليم سريع',
    fastDeliveryDesc: 'معالجة وتسليم سريع إلى بابك',
    learnMore: 'اعرف المزيد عنا',
    
    // Contact
    readyToFind: 'هل أنت مستعد للعثور على سيارة أحلامك؟',
    contactDesc: 'قم بزيارة صالة العرض الخاصة بنا أو تواصل مع فريق الخبراء لدينا. نحن هنا لمساعدتك في العثور على السيارة المثالية التي تناسب أسلوبك وميزانيتك.',
    callUs: 'اتصل بنا',
    emailUs: 'راسلنا عبر البريد',
    visitUs: 'قم بزيارتنا',
    scheduleVisit: 'حدد موعد زيارة',
    getQuote: 'احصل على عرض سعر',
    
    // Footer
    footerDesc: 'شريكك الموثوق في العثور على السيارة المثالية. الجودة والفخامة والموثوقية في كل اختيار.',
    company: 'الشركة',
    services: 'الخدمات',
    support: 'الدعم',
    legal: 'قانوني',
    newsletter: 'اشترك في نشرتنا الإخبارية',
    newsleterDesc: 'احصل على آخر التحديثات حول السيارات الجديدة والعروض الحصرية.',
    emailPlaceholder: 'أدخل بريدك الإلكتروني',
    subscribe: 'اشترك',
    allRightsReserved: 'جميع الحقوق محفوظة',
    privacyPolicy: 'سياسة الخصوصية',
    termsOfService: 'شروط الخدمة',
    sitemap: 'خريطة الموقع',
    
    // About Page
    aboutPageTitle: 'معلومات عنا',
    aboutPageSlogan: 'نقود التميز منذ 2009',
    ourMission: 'مهمتنا',
    missionText: 'تقديم حلول سيارات استثنائية من خلال سيارات عالية الجودة، أسعار شفافة، وخدمة عملاء لا مثيل لها. نؤمن أن كل رحلة تبدأ بالسيارة المناسبة.',
    ourVision: 'رؤيتنا',
    visionText: 'أن نصبح الشريك الأكثر موثوقية في مجال السيارات من خلال إحداث ثورة في تجربة شراء السيارات بالابتكار والنزاهة والنهج الذي يضع العميل أولاً.',
    ourHistory: 'تاريخنا',
    historyText: 'تأسست دريم كارز في عام 2009، ونمت من شركة عائلية صغيرة إلى واحدة من أبرز وكالات السيارات في المنطقة. رحلتنا بُنيت على الثقة والجودة والشغف بالسيارات.',
    whyChooseUs: 'لماذا تختارنا',
    whyChooseDesc: 'نتميز من خلال التزامنا بالتميز ورضا العملاء',
    certifiedQuality: 'جودة معتمدة',
    certifiedQualityDesc: 'جميع السيارات تخضع لفحص شامل من 150 نقطة',
    transparentPricing: 'أسعار شفافة',
    transparentPricingDesc: 'لا توجد رسوم خفية، أسعار واضحة مع تفاصيل كاملة',
    lifetimeSupport: 'دعم مدى الحياة',
    lifetimeSupportDesc: 'خدمة عملاء 24/7 ومساعدة صيانة',
    flexibleFinancing: 'تمويل مرن',
    flexibleFinancingDesc: 'خطط دفع مخصصة تناسب ميزانيتك',
    ourServices: 'خدماتنا',
    servicesDesc: 'حلول سيارات شاملة لجميع احتياجاتك',
    carSales: 'بيع السيارات',
    carSalesDesc: 'مجموعة واسعة من السيارات الجديدة والمستعملة المعتمدة من أفضل العلامات',
    financing: 'التمويل',
    financingDesc: 'أسعار تنافسية وخيارات دفع مرنة مصممة لك',
    tradeIn: 'استبدال السيارة',
    tradeInDesc: 'قيمة سوقية عادلة لسيارتك الحالية مع عروض فورية',
    maintenance: 'الصيانة والخدمة',
    maintenanceDesc: 'فنيون خبراء وقطع أصلية لجميع الماركات والموديلات',
    insurance: 'التأمين',
    insuranceDesc: 'خيارات تغطية شاملة من شركاء تأمين موثوقين',
    warranty: 'ضمان ممتد',
    warrantyDesc: 'راحة البال مع برامج الضمان الشاملة لدينا',
    meetOurTeam: 'تعرف على فريقنا',
    teamDesc: 'محترفون متفانون لتلبية احتياجاتك في مجال السيارات',
    salesDirector: 'مدير المبيعات',
    serviceManager: 'مدير الخدمة',
    financeAdvisor: 'مستشار مالي',
    customerRelations: 'علاقات العملاء',
    getInTouch: 'تواصل معنا',
    getInTouchDesc: 'قم بزيارة صالة العرض أو اتصل بنا لأي استفسارات',
    ourLocation: 'موقعنا',
    businessHours: 'ساعات العمل',
    mondayFriday: 'الإثنين - الجمعة',
    saturday: 'السبت',
    sunday: 'الأحد',
    viewOnMap: 'عرض على خرائط جوجل',
    
    // Cars Page
    availableCars: 'السيارات المتاحة',
    browseCars: 'تصفح السيارات',
    carsPageDesc: 'اكتشف سيارتك المثالية من مجموعتنا الواسعة',
    searchPlaceholder: 'البحث بالعلامة التجارية أو الطراز أو السنة...',
    filters: 'التصفية',
    allBrands: 'كل العلامات',
    allModels: 'كل الموديلات',
    allYears: 'كل السنوات',
    fuelType: 'نوع الوقود',
    allFuelTypes: 'كل أنواع الوقود',
    transmission: 'ناقل الحركة',
    allTransmissions: 'كل أنواع ناقل الحركة',
    priceRange: 'نطاق السعر',
    minPrice: 'الحد الأدنى',
    maxPrice: 'الحد الأقصى',
    resetFilters: 'إعادة تعيين',
    applyFilters: 'تطبيق',
    sortBy: 'ترتيب حسب',
    priceLowToHigh: 'السعر: من الأقل للأعلى',
    priceHighToLow: 'السعر: من الأعلى للأقل',
    yearNewest: 'السنة: الأحدث أولاً',
    yearOldest: 'السنة: الأقدم أولاً',
    brandAZ: 'العلامة: أ-ي',
    brandZA: 'العلامة: ي-أ',
    showingResults: 'عرض',
    of: 'من',
    results: 'نتيجة',
    noResults: 'لم يتم العثور على سيارات',
    noResultsDesc: 'حاول تعديل الفلاتر أو مصطلحات البحث',
    clearFilters: 'مسح جميع الفلاتر',
    new: 'جديد',
    used: 'مستعمل',
    certified: 'مستعمل معتمد',
    electric: 'كهربائي',
    hybrid: 'هجين',
    gasoline: 'بنزين',
    diesel: 'ديزل',
    automatic: 'أوتوماتيك',
    manual: 'يدوي',
    semiAutomatic: 'نصف أوتوماتيك',
    loadMore: 'تحميل المزيد',
    loading: 'جاري التحميل...',
    perPage: 'لكل صفحة',
    startingPrice: 'السعر الابتدائي',
    allConditions: 'كل الحالات',
    condition: 'الحالة',
    
    // Car Details Page
    carDetails: 'تفاصيل السيارة',
    specifications: 'المواصفات',
    features: 'المميزات والمعدات',
    description: 'الوصف',
    overview: 'نظرة عامة',
    version: 'الإصدار',
    doors: 'الأبواب',
    seats: 'المقاعد',
    engineCapacity: 'المحرك',
    vinNumber: 'رقم الهيكل',
    availability: 'التوفر',
    available: 'متاح',
    reserved: 'محجوز',
    sold: 'مباع',
    discount: 'خصم',
    finalPrice: 'السعر النهائي',
    reserveNow: 'احجز الآن',
    buyNow: 'اشتر الآن',
    contactDealer: 'اتصل بالوكيل',
    shareThisCar: 'شارك هذه السيارة',
    printDetails: 'طباعة التفاصيل',
    compareVehicles: 'مقارنة المركبات',
    scheduleTestDrive: 'جدولة قيادة تجريبية',
    financing: 'خيارات التمويل',
    tradeIn: 'قيمة المقايضة',
    warranty: 'معلومات الضمان',
    luxuryPerformance: 'الفخامة والأداء',
    premiumFeatures: 'المميزات الفاخرة',
    advancedTech: 'التكنولوجيا المتقدمة',
    exceptionalComfort: 'الراحة الاستثنائية',
    
    // Contact Page
    contactUs: 'اتصل بنا',
    getInTouch: 'تواصل معنا',
    contactDescription: 'هل لديك سؤال أو ترغب في جدولة قيادة تجريبية؟ نحن هنا للمساعدة! تواصل معنا وسيقوم فريقنا بالرد عليك في أقرب وقت ممكن.',
    contactInfo: 'معلومات الاتصال',
    ourLocation: 'موقعنا',
    sendMessage: 'أرسل لنا رسالة',
    fullName: 'الاسم الكامل',
    email: 'البريد الإلكتروني',
    phone: 'رقم الهاتف',
    subject: 'الموضوع',
    message: 'الرسالة',
    submit: 'إرسال الرسالة',
    submitting: 'جاري الإرسال...',
    messageSent: 'تم إرسال الرسالة بنجاح!',
    messageError: 'فشل إرسال الرسالة. يرجى المحاولة مرة أخرى.',
    address: 'العنوان',
    workingHours: 'ساعات العمل',
    mondayFriday: 'الإثنين - الجمعة',
    saturday: 'السبت',
    sunday: 'الأحد',
    closed: 'مغلق',
    callUs: 'اتصل بنا',
    emailUs: 'راسلنا',
    visitUs: 'زرنا',
    followUs: 'تابعنا',
    generalInquiry: 'استفسار عام',
    testDrive: 'طلب قيادة تجريبية',
    salesQuestion: 'سؤال عن المبيعات',
    serviceSupport: 'الخدمة والدعم',
    other: 'أخرى',
    required: 'هذا الحقل مطلوب',
    invalidEmail: 'يرجى إدخال بريد إلكتروني صالح',
    invalidPhone: 'يرجى إدخال رقم هاتف صالح',
    
    // Registration/Inscription Page
    clientRegistration: 'تسجيل العميل',
    inscription: 'التسجيل',
    registrationDescription: 'أكمل النموذج أدناه للتسجيل وحجز سيارة أحلامك. جميع الحقول المميزة بـ * مطلوبة.',
    personalInfo: 'المعلومات الشخصية',
    nationality: 'الجنسية',
    nationalId: 'رقم الهوية الوطنية / جواز السفر',
    streetAddress: 'عنوان الشارع',
    city: 'المدينة',
    country: 'الدولة',
    zipCode: 'الرمز البريدي',
    carSelection: 'اختيار السيارة',
    selectCar: 'اختر سيارة',
    selectedCar: 'السيارة المحددة',
    noCar: 'لم يتم اختيار سيارة',
    carPrice: 'سعر السيارة',
    paymentInfo: 'معلومات الدفع',
    paymentMethod: 'طريقة الدفع',
    cash: 'نقداً',
    bankTransfer: 'تحويل بنكي',
    creditCard: 'بطاقة ائتمان',
    financing: 'التمويل',
    paymentAmount: 'مبلغ الدفع',
    referenceNumber: 'الرقم المرجعي',
    transactionId: 'معرف المعاملة',
    documentUpload: 'تحميل المستندات',
    uploadDocuments: 'تحميل المستندات المطلوبة',
    idCard: 'بطاقة الهوية / جواز السفر',
    driversLicense: 'رخصة القيادة',
    proofOfResidence: 'إثبات الإقامة',
    paymentProof: 'إثبات الدفع',
    uploadFile: 'تحميل الملف',
    fileUploaded: 'تم تحميل الملف',
    removeFile: 'إزالة الملف',
    dragDrop: 'اسحب وأفلت أو انقر للتحميل',
    termsAndConditions: 'الشروط والأحكام',
    acceptTerms: 'أوافق على الشروط والأحكام وسياسة الخصوصية',
    signature: 'التوقيع',
    typeYourName: 'اكتب اسمك الكامل كتوقيع',
    confirmRegistration: 'تأكيد التسجيل',
    processing: 'جاري المعالجة...',
    registrationSuccess: 'تم التسجيل بنجاح!',
    registrationError: 'فشل التسجيل. يرجى المحاولة مرة أخرى.',
    certificateGenerated: 'تم إنشاء شهادة التسجيل الخاصة بك بنجاح.',
    trackingCode: 'رمز التتبع',
    downloadCertificate: 'تحميل الشهادة',
    registrationSummary: 'ملخص التسجيل',
    backToHome: 'العودة إلى الصفحة الرئيسية',
    stepOf: 'الخطوة {current} من {total}',
    next: 'التالي',
    previous: 'السابق',
    dateOfBirth: 'تاريخ الميلاد',
    gender: 'الجنس',
    male: 'ذكر',
    female: 'أنثى',
    preferNotToSay: 'أفضل عدم الإفصاح',
  }
};

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState('en');

  useEffect(() => {
    const savedLanguage = localStorage.getItem('language') || 'en';
    setLanguage(savedLanguage);
    document.documentElement.lang = savedLanguage;
    document.documentElement.dir = savedLanguage === 'ar' ? 'rtl' : 'ltr';
  }, []);

  const changeLanguage = (lang) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
    document.documentElement.lang = lang;
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
  };

  const t = (key) => {
    return translations[language][key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
